const recipesData = [
  {
    id: 1,
    name: 'Roasted vegetables',
    products: ['potatoes', 'mushrooms', 'zucchini', 'paprika'],
    image: 'images/roastedVegetables.jpg',
    instruction:
      'Cut vegetables in slices. Add spices and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 2,
    name: 'Roasted potatoes and paprika',
    products: ['potatoes', 'paprika'],
    image: 'images/roastedVegetables.jpg',
    instruction:
      'Cut potatoes and paprika in slices. Add spices and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 3,
    name: 'Roasted potatoes',
    products: ['potatoes'],
    image: 'images/roastedVegetables.jpg',
    instruction:
      'Cut potatoes in slices. Add spices and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 4,
    name: 'Roasted potatoes, mushrooms with spices',
    products: ['potatoes', 'mushrooms', 'spices'],
    image: 'images/roastedVegetables.jpg',
    instruction:
      'Cut potatoes and mushrooms in slices. Add spices and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 5,
    name: 'Roasted potatoes, paprika and mushrooms',
    products: ['potatoes', 'mushrooms', 'paprika'],
    image: 'images/roastedVegetables.jpg',
    instruction:
      'Cut potatoes, paprika and mushrooms in slices. Add spices and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 6,
    name: 'Roasted potatoes and zucchini',
    products: ['potatoes', 'zucchini'],
    image: 'images/roastedVegetables.jpg',
    instruction:
      'Cut potatoes and zucchini in slices. Add some spices and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 7,
    name: 'Stuffed peppers with carrots',
    products: ['rice', 'paprika', 'carrots', 'tomatoes', 'spices'],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice until soft, cut carrots in small pieces. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 8,
    name: 'Stuffed peppers with lentils',
    products: ['rice', 'lentils', 'paprika', 'coconutmilk', 'spices'],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice and lentils until soft. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 9,
    name: 'Stuffed peppers with mushrooms',
    products: ['rice', 'paprika', 'mushrooms', 'tomatoes', 'spices'],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice until soft, cut mushrooms in small pieces. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 10,
    name: 'Stuffed peppers with zucchini',
    products: ['rice', 'lentils', 'zucchini', 'tomatoes', 'spices'],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice and lentils until soft, cut zucchini in small pieces. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 11,
    name: 'Stuffed peppers with zucchini and broccoli',
    products: ['rice', 'lentils', 'zucchini', 'broccoli', 'tomatoes', 'spices'],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice and lentils until soft, cut zucchini and broccoli in small pieces. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 12,
    name: 'Stuffed peppers with mushrooms and broccoli',
    products: [
      'rice',
      'lentils',
      'mushrooms',
      'broccoli',
      'tomatoes',
      'spices',
    ],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice and lentils until soft, cut mushrooms and broccoli in small pieces. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 13,
    name: 'Stuffed peppers with mushrooms and carrots',
    products: ['rice', 'lentils', 'mushrooms', 'carrots', 'tomatoes', 'spices'],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice and lentils until soft, cut mushrooms and carrots in small pieces. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 14,
    name: 'Stuffed peppers with tomatoes and carrots',
    products: ['rice', 'lentils', 'paprika', 'carrots', 'tomatoes', 'spices'],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice and lentils until soft, cut carrots in small pieces. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 15,
    name: 'Stuffed peppers with tomatoes and zucchini',
    products: ['rice', 'lentils', 'paprika', 'zucchini', 'tomatoes', 'spices'],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice and lentils until soft, cut zucchini in small pieces. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 16,
    name: 'Stuffed peppers with tomatoes, broccoli and zucchini',
    products: [
      'rice',
      'lentils',
      'paprika',
      'broccoli',
      'zucchini',
      'tomatoes',
      'spices',
    ],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice and lentils until soft, cut zucchini and broccoli in small pieces. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 17,
    name: 'Stuffed peppers with tomatoes, carrots and zucchini',
    products: [
      'rice',
      'lentils',
      'paprika',
      'carrots',
      'zucchini',
      'tomatoes',
      'spices',
    ],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice and lentils until soft, cut zucchini and carrots in small pieces. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 18,
    name: 'Stuffed peppers with broccoli, carrots and zucchini',
    products: [
      'rice',
      'lentils',
      'broccoli',
      'carrots',
      'zucchini',
      'tomatoes',
      'spices',
    ],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice and lentils until soft, cut zucchini, carrots and broccoli in small pieces. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 19,
    name: 'Stuffed peppers with broccoli, mushrooms, carrots and zucchini',
    products: [
      'rice',
      'lentils',
      'broccoli',
      'carrots',
      'zucchini',
      'tomatoes',
      'mushrooms',
      'spices',
    ],
    image: 'images/stuffedPeppers.jpg',
    instruction:
      'Cook rice and lentils until soft, cut zucchini, mushrooms, carrots and broccoli in small pieces. Mix everything and add tomatoes. Fill paprika with mixture and put them in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 20,
    name: 'Stuffed zucchini with mushrooms',
    products: ['rice', 'mushrooms', 'zucchini', 'coconutmilk', 'spices'],
    image: 'images/stuffedZucchini.jpg',
    instruction:
      'Cook rice until soft, cut mushrooms in small pieces. Mix them with coconut milk and put zucchini with the mixture in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 21,
    name: 'Stuffed zucchini with paprika and lentils',
    products: [
      'rice',
      'zucchini',
      'lentils',
      'paprika',
      'coconutmilk',
      'spices',
    ],
    image: 'images/stuffedZucchini.jpg',
    instruction:
      'Cook rice and lentils until soft, cut paprika in small pieces Mix everything with coconut milk and put zucchini with the mixture in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 22,
    name: 'Stuffed zucchini with carrots',
    products: ['rice', 'carrots', 'zucchini', 'coconutmilk', 'spices'],
    image: 'images/stuffedZucchini.jpg',
    instruction:
      'Cook rice and carrots until soft. Mix them with coconut milk and put zucchini with the mixture in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 23,
    name: 'Stuffed zucchini with paprika',
    products: ['rice', 'paprika', 'zucchini', 'coconutmilk', 'spices'],
    image: 'images/stuffedZucchini.jpg',
    instruction:
      'Cook rice until soft. Mix it with paprika and coconut milk and put zucchini with the mixture in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 24,
    name: 'Stuffed zucchini with paprika and mushrooms',
    products: [
      'rice',
      'paprika',
      'zucchini',
      'mushrooms',
      'coconutmilk',
      'spices',
    ],
    image: 'images/stuffedZucchini.jpg',
    instruction:
      'Cook rice until soft. Mix it with paprika, mushrooms and coconut milk and put zucchini with the mixture in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 25,
    name: 'Stuffed zucchini with broccoli and lentils',
    products: [
      'rice',
      'broccoli',
      'zucchini',
      'lentils',
      'coconutmilk',
      'spices',
    ],
    image: 'images/stuffedZucchini.jpg',
    instruction:
      'Cook rice and lentils until soft. Mix it with broccoli and coconut milk and put zucchini with the mixture in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 26,
    name: 'Stuffed zucchini with broccoli and mushrooms',
    products: [
      'rice',
      'broccoli',
      'zucchini',
      'mushrooms',
      'coconutmilk',
      'spices',
    ],
    image: 'images/stuffedZucchini.jpg',
    instruction:
      'Cook rice until soft. Mix it with broccoli, mushrooms and coconut milk and put zucchini with the mixture in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 27,
    name: 'Stuffed zucchini with broccoli and carrots',
    products: [
      'rice',
      'broccoli',
      'zucchini',
      'carrots',
      'coconutmilk',
      'spices',
    ],
    image: 'images/stuffedZucchini.jpg',
    instruction:
      'Cook rice until soft. Mix it with broccoli, carrots and coconut milk and put zucchini with the mixture in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 28,
    name: 'Stuffed zucchini with paprika and carrots',
    products: [
      'rice',
      'paprika',
      'zucchini',
      'carrots',
      'coconutmilk',
      'spices',
    ],
    image: 'images/stuffedZucchini.jpg',
    instruction:
      'Cook rice until soft. Mix it with paprika, carrots and coconut milk and put zucchini with the mixture in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 29,
    name: 'Stuffed zucchini with paprika, mushrooms and carrots',
    products: [
      'rice',
      'paprika',
      'zucchini',
      'mushrooms',
      'carrots',
      'coconutmilk',
      'spices',
    ],
    image: 'images/stuffedZucchini.jpg',
    instruction:
      'Cook rice until soft. Mix it with paprika, mushrooms, carrots and coconut milk and put zucchini with the mixture in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 30,
    name: 'Stuffed zucchini with lentils, mushrooms and carrots',
    products: [
      'rice',
      'lentils',
      'zucchini',
      'mushrooms',
      'carrots',
      'coconutmilk',
      'spices',
    ],
    image: 'images/stuffedZucchini.jpg',
    instruction:
      'Cook rice until soft. Mix it with lentils, mushrooms, carrots and coconut milk and put zucchini with the mixture in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 31,
    name: 'Stuffed zucchini with lentils, mushrooms, broccoli and carrots',
    products: [
      'rice',
      'lentils',
      'zucchini',
      'broccoli',
      'mushrooms',
      'carrots',
      'coconutmilk',
      'spices',
    ],
    image: 'images/stuffedZucchini.jpg',
    instruction:
      'Cook rice and lentils until soft. Mix it with mushrooms, broccoli, carrots and coconut milk and put zucchini with the mixture in the oven at 180° for about 45 minutes.',
    isBookmarked: false,
  },
  {
    id: 32,
    name: 'Pasta with mushrooms',
    products: ['pasta', 'mushrooms', 'coconutmilk', 'spices'],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta until soft, cut mushrooms in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 33,
    name: 'Pasta with mushrooms and carrots',
    products: ['pasta', 'mushrooms', 'carrots', 'coconutmilk', 'spices'],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta until soft, cut mushrooms and carrots in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 34,
    name: 'Pasta with mushrooms and broccoli',
    products: ['pasta', 'mushrooms', 'broccoli', 'coconutmilk', 'spices'],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta until soft, cut mushrooms and broccoli in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 35,
    name: 'Pasta with mushrooms and paprika',
    products: ['pasta', 'mushrooms', 'paprika', 'coconutmilk', 'spices'],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta until soft, cut mushrooms and paprika in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 36,
    name: 'Pasta with mushrooms and lentils',
    products: ['pasta', 'mushrooms', 'lentils', 'coconutmilk', 'spices'],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta and lentils until soft, cut mushrooms in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 37,
    name: 'Pasta with mushrooms and zucchini',
    products: ['pasta', 'mushrooms', 'zucchini', 'coconutmilk', 'spices'],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta until soft, cut mushrooms and zucchini in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 38,
    name: 'Pasta with mushrooms, paprika and zucchini',
    products: [
      'pasta',
      'mushrooms',
      'paprika',
      'zucchini',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta until soft, cut mushrooms, paprika and zucchini in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 39,
    name: 'Pasta with mushrooms, paprika and carrots',
    products: [
      'pasta',
      'mushrooms',
      'paprika',
      'carrots',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta until soft, cut mushrooms, paprika and carrots in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 40,
    name: 'Pasta with mushrooms, paprika and broccoli',
    products: [
      'pasta',
      'mushrooms',
      'paprika',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta until soft, cut mushrooms, paprika and broccoli in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 41,
    name: 'Pasta with mushrooms, lentils and broccoli',
    products: [
      'pasta',
      'mushrooms',
      'lentils',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta and lentils until soft, cut mushrooms and broccoli in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 42,
    name: 'Pasta with mushrooms, lentils, tomatoes and broccoli',
    products: [
      'pasta',
      'mushrooms',
      'lentils',
      'broccoli',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta and lentils until soft, cut mushrooms, tomatoes and broccoli in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 43,
    name: 'Pasta with mushrooms, carrots, tomatoes and broccoli',
    products: [
      'pasta',
      'mushrooms',
      'carrots',
      'broccoli',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta until soft, cut mushrooms, carrots, tomatoes and broccoli in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 44,
    name: 'Pasta with mushrooms, carrots, tomatoes and paprika',
    products: [
      'pasta',
      'mushrooms',
      'carrots',
      'paprika',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta until soft, cut mushrooms, carrots, tomatoes and paprika in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 45,
    name: 'Pasta with mushrooms, carrots, tomatoes, broccoli and paprika',
    products: [
      'pasta',
      'mushrooms',
      'carrots',
      'paprika',
      'tomatoes',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaMushrooms.jpg',
    instruction:
      'Cook pasta until soft, cut mushrooms, carrots, tomatoes, broccoli and paprika in pieces and put everything in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 46,
    name: 'Vegan patties with potatoes and broccoli',
    products: ['potatoes', 'lentils', 'rice', 'tomatoes', 'broccoli', 'spices'],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 47,
    name: 'Vegan patties with potatoes and carrots',
    products: ['potatoes', 'lentils', 'rice', 'tomatoes', 'carrots', 'spices'],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 48,
    name: 'Vegan patties with potatoes and paprika',
    products: ['potatoes', 'lentils', 'rice', 'paprika', 'tomatoes', 'spices'],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 49,
    name: 'Vegan patties with potatoes and zucchini',
    products: ['potatoes', 'lentils', 'rice', 'zucchini', 'tomatoes', 'spices'],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 50,
    name: 'Vegan patties with potatoes and mushrooms',
    products: [
      'potatoes',
      'lentils',
      'rice',
      'mushrooms',
      'tomatoes',
      'spices',
    ],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 51,
    name: 'Vegan patties with potatoes, broccoli and mushrooms',
    products: [
      'potatoes',
      'lentils',
      'rice',
      'mushrooms',
      'broccoli',
      'tomatoes',
      'spices',
    ],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 52,
    name: 'Vegan patties with potatoes, broccoli and carrots',
    products: [
      'potatoes',
      'lentils',
      'rice',
      'carrots',
      'broccoli',
      'tomatoes',
      'spices',
    ],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 53,
    name: 'Vegan patties with potatoes, paprika and carrots',
    products: [
      'potatoes',
      'lentils',
      'rice',
      'carrots',
      'paprika',
      'tomatoes',
      'spices',
    ],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 54,
    name: 'Vegan patties with potatoes, zucchini and carrots',
    products: [
      'potatoes',
      'lentils',
      'rice',
      'carrots',
      'zucchini',
      'tomatoes',
      'spices',
    ],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 55,
    name: 'Vegan patties with potatoes, zucchini, paprika and carrots',
    products: [
      'potatoes',
      'lentils',
      'rice',
      'carrots',
      'zucchini',
      'paprika',
      'tomatoes',
      'spices',
    ],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 56,
    name: 'Vegan patties with potatoes, zucchini, broccoli and carrots',
    products: [
      'potatoes',
      'lentils',
      'rice',
      'carrots',
      'zucchini',
      'broccoli',
      'tomatoes',
      'spices',
    ],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 57,
    name: 'Vegan patties with potatoes, mushrooms, broccoli and carrots',
    products: [
      'potatoes',
      'lentils',
      'rice',
      'carrots',
      'mushrooms',
      'broccoli',
      'tomatoes',
      'spices',
    ],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 58,
    name: 'Vegan patties with potatoes, mushrooms, paprika and carrots',
    products: [
      'potatoes',
      'lentils',
      'rice',
      'carrots',
      'mushrooms',
      'paprika',
      'tomatoes',
      'spices',
    ],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 59,
    name: 'Vegan patties with potatoes, mushrooms, paprika and zucchini',
    products: [
      'potatoes',
      'lentils',
      'rice',
      'zucchini',
      'mushrooms',
      'paprika',
      'tomatoes',
      'spices',
    ],
    image: 'images/patties.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 60,
    name: 'Potato and carrot pancakes with mixed vegetables',
    products: [
      'potatoes',
      'carrots',
      'lentils',
      'broccoli',
      'paprika',
      'zucchini',
      'spices',
      'coconutmilk',
    ],
    image: 'images/potatoePancakes.jpg',
    instruction:
      'Cook rice, potatoes and lentils until soft. Mix rice, lentils and add spices and form burger patties. Roast them in a pan. Serve patties wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 61,
    name: 'Potatoe-carrot pancakes with paprika',
    products: ['potatoes', 'carrots', 'paprika', 'spices', 'tomatoes'],
    image: 'images/potatoePancakes.jpg',
    instruction:
      'Cook potatoes and carrots until soft. Mix them and add spices and form small pancakes. Roast them in a pan. Serve pancakes wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 62,
    name: 'Potatoe-carrot pancakes with paprika and lentils',
    products: ['potatoes', 'carrots', 'paprika', 'lentils', 'spices'],
    image: 'images/potatoePancakes.jpg',
    instruction:
    'Cook potatoes and carrots until soft. Mix them and add spices and form small pancakes. Roast them in a pan. Serve pancakes wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 63,
    name: 'Potatoe-carrot pancakes with broccoli',
    products: ['potatoes', 'carrots', 'broccoli', 'spices', 'coconutmilk'],
    image: 'images/potatoePancakes.jpg',
    instruction:
    'Cook potatoes and carrots until soft. Mix them and add spices and form small pancakes. Roast them in a pan. Serve pancakes wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 64,
    name: 'Potatoe-carrot pancakes with zucchini',
    products: ['potatoes', 'carrots', 'zucchini', 'spices', 'coconutmilk'],
    image: 'images/potatoePancakes.jpg',
    instruction:
    'Cook potatoes and carrots until soft. Mix them and add spices and form small pancakes. Roast them in a pan. Serve pancakes wtih potatoes and vegetables.',
    isBookmarked: false,
  },
  {
    id: 65,
    name: 'Rice with broccoli and carrots',
    products: ['rice', 'carrots', 'broccoli', 'coconutmilk', 'spices'],
    image: 'images/riceVegetable.jpg',
    instruction:
      'Cook rice, broccoli and carrots until soft and mix them in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 66,
    name: 'Rice with paprika and broccoli',
    products: ['rice', 'carrots', 'paprika', 'broccoli', 'tomatoes', 'spices'],
    image: 'images/riceVegetable.jpg',
    instruction:
      'Cook rice carrots until soft and mix rice with vegetables in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 67,
    name: 'Rice with paprika and mushrooms',
    products: ['rice', 'paprika', 'mushrooms', 'tomatoes', 'spices'],
    image: 'images/riceVegetable.jpg',
    instruction:
      'Cook rice until soft and mix it with vegetables in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 68,
    name: 'Rice with broccoli and mushrooms',
    products: ['rice', 'mushrooms', 'tomatoes', 'broccoli', 'spices'],
    image: 'images/riceVegetable.jpg',
    instruction:
      'Cook rice until soft and mix it with vegetables in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 69,
    name: 'Rice with broccoli and lentils',
    products: ['rice', 'broccoli', 'lentils', 'coconutmilk', 'spices'],
    image: 'images/riceVegetable.jpg',
    instruction:
      'Cook rice and lentils until soft and mix them with vegetables in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 70,
    name: 'Rice with carrots and lentils',
    products: ['rice', 'carrots', 'lentils', 'coconutmilk', 'spices'],
    image: 'images/riceVegetable.jpg',
    instruction:
      'Cook rice and lentils until soft and mix them with vegetables in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 71,
    name: 'Rice with broccoli, carrots and lentils',
    products: [
      'rice',
      'carrots',
      'broccoli',
      'lentils',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceVegetable.jpg',
    instruction:
      'Cook rice and lentils until soft and mix them with vegetables in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 72,
    name: 'Rice with broccoli, carrots, paprika and lentils',
    products: [
      'rice',
      'carrots',
      'paprika',
      'broccoli',
      'lentils',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceVegetable.jpg',
    instruction:
      'Cook rice and lentils until soft and mix them with vegetables in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 73,
    name: 'Rice with broccoli, carrots, zucchini and lentils',
    products: [
      'rice',
      'carrots',
      'zucchini',
      'broccoli',
      'lentils',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceVegetable.jpg',
    instruction:
      'Cook rice and lentils until soft and mix them with vegetables in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 74,
    name: 'Rice with broccoli, mushrooms, zucchini and lentils',
    products: [
      'rice',
      'mushrooms',
      'zucchini',
      'broccoli',
      'lentils',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceVegetable.jpg',
    instruction:
      'Cook rice and lentils until soft and mix them with vegetables in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 75,
    name: 'Rice with broccoli, mushrooms, zucchini and paprika',
    products: [
      'rice',
      'mushrooms',
      'zucchini',
      'broccoli',
      'paprika',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceVegetable.jpg',
    instruction:
      'Cook rice until soft and mix it with vegetables in a panCix rice with vegetables in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 76,
    name: 'Rice with broccoli, mushrooms, lentils and paprika',
    products: [
      'rice',
      'mushrooms',
      'lentils',
      'broccoli',
      'paprika',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceVegetable.jpg',
    instruction:
      'Cook rice and lentils until soft and mix them with vegetables in a pan. Add coconut milk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 77,
    name: 'Colourful pasta',
    products: [
      'pasta',
      'carrots',
      'paprika',
      'lentils',
      'zucchini',
      'mushrooms',
      'tomatoes',
      'broccoli',
      'spices',
      'coconutmilk',
    ],
    image: 'images/pastaVegetable.jpg',
    instruction:
      'Cook pasta until soft. Mix pasta with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 78,
    name: 'Colourful pasta with carrots and broccoli',
    products: ['pasta', 'carrots', 'tomatoes', 'broccoli', 'spices'],
    image: 'images/pastaVegetable.jpg',
    instruction:
      'Cook pasta until soft. Mix pasta with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 79,
    name: 'Colourful pasta with carrots and lentils',
    products: ['pasta', 'carrots', 'lentils', 'zucchini', 'tomatoes', 'spices'],
    image: 'images/pastaVegetable.jpg',
    instruction:
      'Cook pasta until soft. Mix pasta with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 80,
    name: 'Colourful pasta with zucchini and broccoli',
    products: ['pasta', 'broccoli', 'zucchini', 'spices', 'coconutmilk'],
    image: 'images/pastaVegetable.jpg',
    instruction:
      'Cook pasta until soft. Mix pasta with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 81,
    name: 'Colourful pasta with paprika and carrots',
    products: [
      'pasta',
      'carrots',
      'paprika',
      'tomatoes',
      'spices',
      'coconutmilk',
    ],
    image: 'images/pastaVegetable.jpg',
    instruction:
      'Cook pasta until soft. Mix pasta with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 82,
    name: 'Colourful pasta with paprika',
    products: ['pasta', 'paprika', 'tomatoes', 'spices'],
    image: 'images/pastaVegetable.jpg',
    instruction:
      'Cook pasta until soft. Mix pasta with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 83,
    name: 'Colourful pasta with broccoli',
    products: ['pasta', 'broccoli', 'tomatoes', 'spices'],
    image: 'images/pastaVegetable.jpg',
    instruction:
      'Cook pasta until soft. Mix pasta with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 84,
    name: 'Colourful pasta with zucchini',
    products: ['pasta', 'zucchini', 'tomatoes', 'spices'],
    image: 'images/pastaVegetable.jpg',
    instruction:
      'Cook pasta until soft. Mix pasta with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 85,
    name: 'Colourful pasta with zucchini, lentils and carrots',
    products: ['pasta', 'zucchini', 'lentils', 'carrots', 'tomatoes', 'spices'],
    image: 'images/pastaVegetable.jpg',
    instruction:
      'Cook pasta until soft. Mix pasta with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 86,
    name: 'Colourful pasta with mushrooms, lentils and carrots',
    products: [
      'pasta',
      'mushrooms',
      'lentils',
      'carrots',
      'tomatoes',
      'spices',
    ],
    image: 'images/pastaVegetable.jpg',
    instruction:
      'Cook pasta until soft. Mix pasta with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 87,
    name: 'Colourful pasta with mushrooms and paprika',
    products: ['pasta', 'mushrooms', 'paprika', 'tomatoes', 'spices'],
    image: 'images/pastaVegetable.jpg',
    instruction:
      'Cook pasta until soft. Mix pasta with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 88,
    name: 'Braised vegetables with potatoes',
    products: [
      'potatoes',
      'carrots',
      'paprika',
      'lentils',
      'zucchini',
      'mushrooms',
      'tomatoes',
      'broccoli',
      'spices',
      'coconutmilk',
    ],
    image: 'images/potatoVegetable.jpeg',
    instruction:
      'Cook potatoes until soft. Mix potatoes with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 89,
    name: 'Braised broccoli and zucchini with potatoes',
    products: ['potatoes', 'broccoli', 'zucchini', 'spices', 'coconutmilk'],
    image: 'images/potatoVegetable.jpeg',
    instruction:
      'Cook potatoes until soft. Mix potatoes with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 90,
    name: 'Braised carrots and paprika with potatoes',
    products: [
      'potatoes',
      'carrots',
      'paprika',
      'tomatoes',
      'zucchini',
      'spices',
    ],
    image: 'images/potatoVegetable.jpeg',
    instruction:
      'Cook potatoes until soft. Mix potatoes with vegetables in a pan and add tomatoes and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 91,
    name: 'Braised carrots and broccoli with potatoes',
    products: ['potatoes', 'carrots', 'zucchini', 'spices', 'coconutmilk'],
    image: 'images/potatoVegetable.jpeg',
    instruction:
      'Cook potatoes until soft. Mix potatoes with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 92,
    name: 'Braised paprika and broccoli with potatoes',
    products: ['potatoes', 'paprika', 'zucchini', 'spices', 'coconutmilk'],
    image: 'images/potatoVegetable.jpeg',
    instruction:
      'Cook potatoes until soft. Mix potatoes with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 93,
    name: 'Braised paprika and mushrooms with potatoes',
    products: ['potatoes', 'paprika', 'mushrooms', 'spices', 'coconutmilk'],
    image: 'images/potatoVegetable.jpeg',
    instruction:
      'Cook potatoes until soft. Mix potatoes with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 94,
    name: 'Braised broccoli and mushrooms with potatoes',
    products: ['potatoes', 'broccoli', 'mushrooms', 'spices', 'coconutmilk'],
    image: 'images/potatoVegetable.jpeg',
    instruction:
      'Cook potatoes until soft. Mix potatoes with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 95,
    name: 'Braised carrots, broccoli and zucchini with potatoes',
    products: [
      'potatoes',
      'carrots',
      'zucchini',
      'tomatoes',
      'broccoli',
      'spices',
    ],
    image: 'images/potatoVegetable.jpeg',
    instruction:
      'Cook potatoes until soft. Mix potatoes with vegetables in a pan and add tomatoes and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 96,
    name: 'Braised broccoli with potatoes',
    products: ['potatoes', 'lentils', 'broccoli', 'spices', 'coconutmilk'],
    image: 'images/potatoVegetable.jpeg',
    instruction:
      'Cook potatoes until soft. Mix potatoes with vegetables in a pan and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 97,
    name: 'Potatoe soup with lentils',
    products: ['potatoes', 'lentils', 'spices', 'coconutmilk'],
    image: 'images/potatoeSoup.jpg',
    instruction:
      'Cook potatoes until soft. Mash potatoes, add coconutmilk and lentils. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 98,
    name: 'Potatoe soup',
    products: ['potatoes', 'spices', 'coconutmilk'],
    image: 'images/potatoeSoup.jpg',
    instruction:
      'Cook potatoes until soft. Mash potatoes and add coconutmilk. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 99,
    name: 'Potatoe and mushroom soup',
    products: ['potatoes', 'mushrooms', 'spices', 'coconutmilk'],
    image: 'images/potatoeMushroomSoup.jpg',
    instruction:
      'Cook potatoes until soft. Mash potatoes and more than half of the mushrooms, add coconutmilk and mushrooms. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 100,
    name: 'Potatoe and mushroom soup with carrots',
    products: ['potatoes', 'mushrooms', 'carrots', 'spices', 'coconutmilk'],
    image: 'images/potatoeMushroomSoup.jpg',
    instruction:
      'Cook potatoes and carrots until soft. Mash them and more than half of the mushrooms, add coconutmilk and mushrooms. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 101,
    name: 'Mushroom soup',
    products: ['mushrooms', 'coconutmilk', 'spices'],
    image: 'images/mushroomSoup.jpg',
    instruction:
      'Mash mushrooms and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 102,
    name: 'Carrot and lentil soup',
    products: ['carrots', 'lentils', 'coconutmilk', 'spices'],
    image: 'images/carrotLentilSoup.jpg',
    instruction:
      'Mash carrots and add coconutmilk, lentils and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 103,
    name: 'Ratatouille with rice',
    products: [
      'rice',
      'mushrooms',
      'zucchini',
      'paprika',
      'tomatoes',
      'spices',
    ],
    image: 'images/ratatouilleRice.jpg',
    instruction:
      'Cook rice until soft. Cut vegetables in small pieces, add spices and cook it for around 10 minutes. Serve ratatouille with rice.',
    isBookmarked: false,
  },
  {
    id: 104,
    name: 'Ratatouille with rice and tomatoes',
    products: ['rice', 'mushrooms', 'carrots', 'paprika', 'tomatoes', 'spices'],
    image: 'images/ratatouilleRice.jpg',
    instruction:
      'Cook rice until soft. Cut vegetables in small pieces, add spices and cook it for around 10 minutes. Serve ratatouille with rice.',
    isBookmarked: false,
  },
  {
    id: 105,
    name: 'Ratatouille with rice and paprika',
    products: ['rice', 'zucchini', 'paprika', 'tomatoes', 'spices'],
    image: 'images/ratatouilleRice.jpg',
    instruction:
      'Cook rice until soft. Cut vegetables in small pieces, add spices and cook it for around 10 minutes. Serve ratatouille with rice.',
    isBookmarked: false,
  },
  {
    id: 106,
    name: 'Ratatouille with rice and carrots',
    products: ['rice', 'carrots', 'paprika', 'tomatoes', 'spices'],
    image: 'images/ratatouilleRice.jpg',
    instruction:
      'Cook rice until soft. Cut vegetables in small pieces, add spices and cook it for around 10 minutes. Serve ratatouille with rice.',
    isBookmarked: false,
  },
  {
    id: 107,
    name: 'Ratatouille with rice and zucchini',
    products: ['rice', 'carrots', 'zucchini', 'tomatoes', 'spices'],
    image: 'images/ratatouilleRice.jpg',
    instruction:
      'Cook rice until soft. Cut vegetables in small pieces, add spices and cook it for around 10 minutes. Serve ratatouille with rice.',
    isBookmarked: false,
  },
  {
    id: 108,
    name: 'Ratatouille with rice and broccoli',
    products: ['rice', 'carrots', 'broccoli', 'tomatoes', 'spices'],
    image: 'images/ratatouilleRice.jpg',
    instruction:
      'Cook rice until soft. Cut vegetables in small pieces, add spices and cook it for around 10 minutes. Serve ratatouille with rice.',
    isBookmarked: false,
  },
  {
    id: 109,
    name: 'Ratatouille with rice, broccoli and carrots',
    products: ['rice', 'carrots', 'broccoli', 'tomatoes', 'spices'],
    image: 'images/ratatouilleRice.jpg',
    instruction:
      'Cook rice until soft. Cut vegetables in small pieces, add spices and cook it for around 10 minutes. Serve ratatouille with rice.',
    isBookmarked: false,
  },
  {
    id: 110,
    name: 'Ratatouille with rice, zucchini and carrots',
    products: ['rice', 'carrots', 'zucchini', 'tomatoes', 'spices'],
    image: 'images/ratatouilleRice.jpg',
    instruction:
      'Cook rice until soft. Cut vegetables in small pieces, add spices and cook it for around 10 minutes. Serve ratatouille with rice.',
    isBookmarked: false,
  },
  {
    id: 111,
    name: 'Ratatouille with rice, zucchini and paprika',
    products: ['rice', 'paprika', 'zucchini', 'tomatoes', 'spices'],
    image: 'images/ratatouilleRice.jpg',
    instruction:
      'Cook rice until soft. Cut vegetables in small pieces, add spices and cook it for around 10 minutes. Serve ratatouille with rice.',
    isBookmarked: false,
  },
  {
    id: 112,
    name: 'Ratatouille with rice, zucchini, carrots and paprika',
    products: ['rice', 'paprika', 'zucchini', 'carrots', 'tomatoes', 'spices'],
    image: 'images/ratatouilleRice.jpg',
    instruction:
      'Cook rice until soft. Cut vegetables in small pieces, add spices and cook it for around 10 minutes. Serve ratatouille with rice.',
    isBookmarked: false,
  },
  {
    id: 113,
    name: 'Ratatouille with rice, zucchini, carrots, broccoli and paprika',
    products: [
      'rice',
      'paprika',
      'zucchini',
      'broccoli',
      'carrots',
      'tomatoes',
      'spices',
    ],
    image: 'images/ratatouilleRice.jpg',
    instruction:
      'Cook rice until soft. Cut vegetables in small pieces, add spices and cook it for around 10 minutes. Serve ratatouille with rice.',
    isBookmarked: false,
  },
  {
    id: 114,
    name: 'Carrot soup',
    products: ['carrots', 'coconutmilk', 'spices'],
    image: 'images/carrotSoup.jpg',
    instruction:
      'Mash carrots and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 115,
    name: 'Tomato soup',
    products: ['tomatoes', 'coconutmilk', 'spices'],
    image: 'images/tomatoeSoup.jpeg',
    instruction:
      'Mash tomatoes and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 116,
    name: 'Tomato soup with lentils',
    products: ['tomatoes', 'lentils', 'coconutmilk', 'spices'],
    image: 'images/tomatoeSoup.jpeg',
    instruction:
      'Mash tomatoes and add coconutmilk, lentils and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 117,
    name: 'Tomato soup with paprika',
    products: ['tomatoes', 'paprika', 'coconutmilk', 'spices'],
    image: 'images/tomatoeSoup.jpeg',
    instruction:
      'Mash tomatoes and add coconutmilk, paprika and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 118,
    name: 'Pasta with mushrooms, zucchini and broccoli',
    products: [
      'pasta',
      'mushrooms',
      'broccoli',
      'zucchini',
      'tomatoes',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut mushrooms and broccoli in pieces and put everything in a pan. Add tomatoes and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 119,
    name: 'Pasta with mushrooms, carrots and broccoli',
    products: [
      'pasta',
      'mushrooms',
      'broccoli',
      'carrots',
      'tomatoes',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut mushrooms, carrots and broccoli in pieces and put everything in a pan. Add tomatoes and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 120,
    name: 'Pasta with zucchini, carrots and broccoli',
    products: [
      'pasta',
      'zucchini',
      'broccoli',
      'carrots',
      'tomatoes',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut zucchini, carrots and broccoli in pieces and put everything in a pan. Add tomatoes and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 121,
    name: 'Pasta with paprika, carrots, mushrooms and broccoli',
    products: [
      'pasta',
      'mushrooms',
      'broccoli',
      'carrots',
      'paprika',
      'tomatoes',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut paprika, carrots, mushrooms and broccoli in pieces and put everything in a pan. Add tomatoes and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 122,
    name: 'Pasta with paprika, carrots, tomatoes, mushrooms and broccoli',
    products: [
      'pasta',
      'mushrooms',
      'broccoli',
      'carrots',
      'paprika',
      'tomatoes',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut paprika, carrots, tomatoes, mushrooms and broccoli in pieces and put everything in a pan. Add tomatoes and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 123,
    name: 'Pasta with paprika, lentils, tomatoes, mushrooms and broccoli',
    products: [
      'pasta',
      'mushrooms',
      'broccoli',
      'lentils',
      'paprika',
      'tomatoes',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut paprika, lentils, tomatoes, mushrooms and broccoli in pieces and put everything in a pan. Add tomatoes and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 124,
    name: 'Pasta with paprika, zucchini and carrots',
    products: [
      'pasta',
      'zucchini',
      'carrots',
      'paprika',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut paprika, zucchini and carrots in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 125,
    name: 'Pasta with paprika, zucchini, lentils and carrots',
    products: [
      'pasta',
      'zucchini',
      'carrots',
      'paprika',
      'lentils',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut paprika, zucchini, lentils and carrots in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 126,
    name: 'Pasta with paprika, mushrooms, lentils and carrots',
    products: [
      'pasta',
      'mushrooms',
      'carrots',
      'paprika',
      'lentils',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut paprika, mushrooms, lentils and carrots in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 127,
    name: 'Pasta with paprika, tomatoes, mushrooms and carrots',
    products: [
      'pasta',
      'mushrooms',
      'carrots',
      'paprika',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut paprika, tomatoes, mushrooms and carrots in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 128,
    name: 'Pasta with paprika, tomatoes, mushrooms and carrots',
    products: [
      'pasta',
      'mushrooms',
      'carrots',
      'paprika',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut paprika, tomatoes, mushrooms and carrots in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 129,
    name: 'Pasta with zucchini, tomatoes and carrots',
    products: [
      'pasta',
      'zucchini',
      'carrots',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut zucchini, tomatoes and carrots in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 130,
    name: 'Pasta with zucchini, paprika, tomatoes and carrots',
    products: [
      'pasta',
      'zucchini',
      'carrots',
      'paprika',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut zucchini, paprika, tomatoes and carrots in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 131,
    name: 'Pasta with zucchini, paprika, tomatoes, mushrooms and carrots',
    products: [
      'pasta',
      'zucchini',
      'mushrooms',
      'carrots',
      'paprika',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut zucchini, paprika, tomatoes, mushrooms and carrots in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 132,
    name: 'Pasta with zucchini, mushrooms and lentils',
    products: [
      'pasta',
      'zucchini',
      'mushrooms',
      'lentils',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta and lentils until soft, cut zucchini and  mushrooms in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 133,
    name: 'Pasta with zucchini, paprika and tomatoes',
    products: [
      'pasta',
      'zucchini',
      'paprika',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut zucchini, paprika and tomatoes in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 134,
    name: 'Pasta with carrots, paprika and tomatoes',
    products: ['pasta', 'carrots', 'paprika', 'tomatoes', 'spices'],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut carrots, paprika and tomatoes in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 135,
    name: 'Pasta with carrots, paprika and broccoli',
    products: [
      'pasta',
      'carrots',
      'paprika',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut carrots, paprika and broccoli in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 136,
    name: 'Pasta with carrots, paprika, zucchini and broccoli',
    products: [
      'pasta',
      'carrots',
      'paprika',
      'zucchini',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut carrots, paprika, zucchini and broccoli in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 137,
    name: 'Pasta with mushrooms, lentils and tomatoes',
    products: [
      'pasta',
      'mushrooms',
      'lentils',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta and lentils until soft, cut mushrooms and tomatoes in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 138,
    name: 'Pasta with mushrooms, carrots, lentils and tomatoes',
    products: [
      'pasta',
      'mushrooms',
      'lentils',
      'carrots',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta and lentils until soft, cut mushrooms, carrots and tomatoes in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 139,
    name: 'Pasta with paprika, carrots and lentils',
    products: [
      'pasta',
      'paprika',
      'lentils',
      'carrots',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta and lentils until soft, cut paprika and carrots in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 140,
    name: 'Pasta with paprika, carrots, broccoli and lentils',
    products: [
      'pasta',
      'paprika',
      'lentils',
      'broccoli',
      'carrots',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta and lentils until soft, cut paprika, carrots and broccoli in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 141,
    name: 'Pasta with carrots and lentils',
    products: ['pasta', 'lentils', 'carrots', 'coconutmilk', 'spices'],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta and lentils until soft, cut carrots in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 142,
    name: 'Pasta with tomatoes and zucchini',
    products: ['pasta', 'tomatoes', 'zucchini', 'coconutmilk', 'spices'],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut  tomatoes and zucchini in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 143,
    name: 'Pasta with tomatoes, broccoli, carrots and paprika',
    products: ['pasta', 'tomatoes', 'broccoli', 'carrots', 'paprika', 'spices'],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut carrots, paprika and broccoli in pieces and put everything in a pan. Add tomatoes and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 144,
    name: 'Pasta with zucchini and carrots',
    products: ['pasta', 'zucchini', 'carrots', 'coconutmilk', 'spices'],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut zucchini and carrots in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 145,
    name: 'Pasta with broccoli, paprika and tomatoes',
    products: [
      'pasta',
      'broccoli',
      'paprika',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut broccoli, paprika and tomatoes in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 146,
    name: 'Pasta with broccoli and tomatoes',
    products: ['pasta', 'broccoli', 'tomatoes', 'coconutmilk', 'spices'],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut broccoli and tomatoes in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 147,
    name: 'Pasta with broccoli, tomatoes and zucchini',
    products: [
      'pasta',
      'broccoli',
      'zucchini',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut broccoli, tomatoes and zucchini in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 148,
    name: 'Pasta with broccoli, tomatoes, paprika and zucchini',
    products: [
      'pasta',
      'broccoli',
      'zucchini',
      'paprika',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/pastaInPan.jpeg',
    instruction:
      'Cook pasta until soft, cut broccoli, tomatoes, paprika and zucchini in pieces and put everything in a pan. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 149,
    name: 'Broccoli soup',
    products: ['broccoli', 'coconutmilk', 'spices'],
    image: 'images/broccoliSoup.jpeg',
    instruction:
      'Cook broccoli until soft. Mash broccoli and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 150,
    name: 'Broccoli soup with carrots',
    products: ['broccoli', 'carrots', 'coconutmilk', 'spices'],
    image: 'images/broccoliSoup.jpeg',
    instruction:
      'Cook broccoli and carrots until soft. Mash vegetables and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 151,
    name: 'Broccoli soup with lentils',
    products: ['broccoli', 'lentils', 'coconutmilk', 'spices'],
    image: 'images/broccoliSoup.jpeg',
    instruction:
      'Cook broccoli and lentils until soft. Mash vegetables and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 152,
    name: 'Broccoli soup with potatoes',
    products: ['broccoli', 'potatoes', 'coconutmilk', 'spices'],
    image: 'images/broccoliSoup.jpeg',
    instruction:
      'Cook broccoli and potatoes until soft. Mash vegetables and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 153,
    name: 'Broccoli soup with potatoes and lentils',
    products: ['broccoli', 'potatoes', 'lentils', 'coconutmilk', 'spices'],
    image: 'images/broccoliSoup.jpeg',
    instruction:
      'Cook broccoli, lentils and potatoes until soft. Mash vegetables and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 154,
    name: 'Broccoli soup with potatoes and carrots',
    products: ['broccoli', 'potatoes', 'carrots', 'coconutmilk', 'spices'],
    image: 'images/broccoliSoup.jpeg',
    instruction:
      'Cook broccoli, carrots and potatoes until soft. Mash vegetables and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 155,
    name: 'Broccoli soup with potatoes, lentils and carrots',
    products: [
      'broccoli',
      'potatoes',
      'lentils',
      'carrots',
      'coconutmilk',
      'spices',
    ],
    image: 'images/broccoliSoup.jpeg',
    instruction:
      'Cook broccoli, lentils, carrots and potatoes until soft. Mash vegetables and add coconutmilk and spices. Cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 156,
    name: 'Potatoes with zucchini, carrots and tomatoes',
    products: ['potatoes', 'zucchini', 'carrots', 'tomatoes', 'spices'],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes, carrots and zucchini until soft. Add tomatoes and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 157,
    name: 'Potatoes with zucchini, carrots, mushrooms and tomatoes',
    products: [
      'potatoes',
      'zucchini',
      'carrots',
      'mushrooms',
      'tomatoes',
      'spices',
    ],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes, zucchini and carrots until soft. Add tomatoes and mushrooms and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 158,
    name: 'Potatoes with zucchini, mushrooms and tomatoes',
    products: ['potatoes', 'zucchini', 'mushrooms', 'tomatoes', 'spices'],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes and zucchini until soft. Add tomatoes, mushrooms and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 159,
    name: 'Potatoes with zucchini, mushrooms, paprika and tomatoes',
    products: [
      'potatoes',
      'zucchini',
      'mushrooms',
      'paprika',
      'tomatoes',
      'spices',
    ],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes and zucchini until soft. Add tomatoes, mushrooms, paprika and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 160,
    name: 'Potatoes with zucchini, paprika and tomatoes',
    products: ['potatoes', 'zucchini', 'paprika', 'tomatoes', 'spices'],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes and zucchini until soft. Add tomatoes, paprika and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 161,
    name: 'Potatoes with zucchini, mushrooms, carrots, paprika and tomatoes',
    products: [
      'potatoes',
      'zucchini',
      'mushrooms',
      'paprika',
      'carrots',
      'tomatoes',
      'spices',
    ],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes, zucchini and carrots until soft. Add tomatoes, mushrooms, paprika and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 162,
    name: 'Potatoes with mushrooms, paprika and tomatoes',
    products: ['potatoes', 'mushrooms', 'paprika', 'tomatoes', 'spices'],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes until soft. Add tomatoes, mushrooms, paprika and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 163,
    name: 'Potatoes with mushrooms, lentils, paprika and tomatoes',
    products: [
      'potatoes',
      'mushrooms',
      'paprika',
      'lentils',
      'tomatoes',
      'spices',
    ],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes and lentils until soft. Add tomatoes, mushrooms, paprika and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 164,
    name: 'Potatoes with zucchini, carrots and paprika',
    products: [
      'potatoes',
      'zucchini',
      'paprika',
      'carrots',
      'coconutmilk',
      'spices',
    ],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes, zucchini and carrots until soft. Add coconutmilk and paprika and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 165,
    name: 'Potatoes with tomatoes, zucchini, carrots and paprika',
    products: [
      'potatoes',
      'zucchini',
      'paprika',
      'carrots',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes, zucchini and carrots until soft. Add tomatoes, coconutmilk, paprika and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 166,
    name: 'Potatoes with tomatoes, zucchini, lentils, carrots and paprika',
    products: [
      'potatoes',
      'zucchini',
      'paprika',
      'carrots',
      'lentils',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes, zucchini, lentils and carrots until soft. Add tomatoes, coconutmilk, paprika and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 167,
    name: 'Potatoes with tomatoes, zucchini and carrots',
    products: [
      'potatoes',
      'zucchini',
      'carrots',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes,  zucchini and carrots until soft. Add tomatoes, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 168,
    name: 'Potatoes with tomatoes, zucchini and mushrooms',
    products: [
      'potatoes',
      'zucchini',
      'mushrooms',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes and zucchini until soft. Add tomatoes, mushrooms, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 169,
    name: 'Potatoes with tomatoes, paprika, zucchini and mushrooms',
    products: [
      'potatoes',
      'zucchini',
      'mushrooms',
      'tomatoes',
      'paprika',
      'coconutmilk',
      'spices',
    ],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes and zucchini until soft. Add tomatoes, mushrooms, paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 170,
    name: 'Potatoes with tomatoes and mushrooms',
    products: ['potatoes', 'mushrooms', 'tomatoes', 'coconutmilk', 'spices'],
    image: 'images/potatoesWithVegetables.jpeg',
    instruction:
      'Cook potatoes until soft. Add tomatoes, mushrooms, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 171,
    name: 'Rice with lentils, zucchini, broccoli and mushrooms',
    products: [
      'rice',
      'mushrooms',
      'lentils',
      'zucchini',
      'tomatoes',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils, zucchini and broccoli until soft. Add tomatoes and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 172,
    name: 'Rice with lentils, zucchini, carrots, broccoli and mushrooms',
    products: [
      'rice',
      'mushrooms',
      'lentils',
      'carrots',
      'zucchini',
      'tomatoes',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils, zucchini, carrots and broccoli until soft. Add tomatoes, mushrooms and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 173,
    name: 'Rice with lentils, zucchini, paprika, broccoli and mushrooms',
    products: [
      'rice',
      'mushrooms',
      'lentils',
      'paprika',
      'zucchini',
      'tomatoes',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils, zucchini and broccoli until soft. Add tomatoes, mushrooms, paprika and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 174,
    name: 'Rice with lentils, paprika, broccoli and mushrooms',
    products: ['rice', 'mushrooms', 'lentils', 'paprika', 'tomatoes', 'spices'],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice lentils and broccoli until soft. Add tomatoes, mushrooms, paprika and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 175,
    name: 'Rice with paprika, broccoli and mushrooms',
    products: ['rice', 'mushrooms', 'paprika', 'tomatoes', 'spices'],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice and broccoli until soft. Add tomatoes, mushrooms, paprika and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 176,
    name: 'Rice with lentils, tomatoes and zucchini',
    products: [
      'rice',
      'lentils',
      'zucchini',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, zucchini and lentils until soft. Add tomatoes, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 177,
    name: 'Rice with lentils, mushrooms, tomatoes and zucchini',
    products: [
      'rice',
      'lentils',
      'mushrooms',
      'zucchini',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice lentils and zucchini until soft. Add tomatoes, mushrooms, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 178,
    name: 'Rice with lentils, paprika, tomatoes and zucchini',
    products: [
      'rice',
      'lentils',
      'paprika',
      'zucchini',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils and zucchini until soft. Add tomatoes, paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 179,
    name: 'Rice with lentils, paprika, tomatoes and mushrooms',
    products: [
      'rice',
      'lentils',
      'paprika',
      'mushrooms',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice and lentils until soft. Add tomatoes, mushrooms, paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 180,
    name: 'Rice with lentils, paprika, carrots, tomatoes and mushrooms',
    products: [
      'rice',
      'lentils',
      'paprika',
      'carrots',
      'mushrooms',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils and carrots, until soft. Add tomatoes, mushrooms, paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 181,
    name: 'Rice with lentils, tomatoes and mushrooms',
    products: [
      'rice',
      'lentils',
      'mushrooms',
      'tomatoes',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice and lentils until soft. Add tomatoes, mushrooms, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 182,
    name: 'Rice with lentils and tomatoes ',
    products: ['rice', 'lentils', 'tomatoes', 'coconutmilk', 'spices'],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice and lentils until soft. Add tomatoes, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 183,
    name: 'Rice with lentils, carrots and paprika ',
    products: [
      'rice',
      'lentils',
      'carrots',
      'paprika',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils and carrots until soft. Add paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 184,
    name: 'Rice with lentils, zucchini, carrots and paprika ',
    products: [
      'rice',
      'lentils',
      'zucchini',
      'carrots',
      'paprika',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils, zucchini and carrots until soft. Add paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 185,
    name: 'Rice with lentils, mushrooms, carrots and paprika ',
    products: [
      'rice',
      'lentils',
      'mushrooms',
      'carrots',
      'paprika',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils and carrots until soft. Add mushrooms, paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 186,
    name: 'Rice with lentils, mushrooms, carrots and broccoli ',
    products: [
      'rice',
      'lentils',
      'mushrooms',
      'carrots',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils, carrots and broccoli until soft. Add mushrooms, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 187,
    name: 'Rice with lentils, mushrooms and broccoli',
    products: [
      'rice',
      'lentils',
      'mushrooms',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils and broccoli until soft. Add mushrooms, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 188,
    name: 'Rice with mushrooms and broccoli',
    products: ['rice', 'mushrooms', 'broccoli', 'coconutmilk', 'spices'],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice and broccoli until soft. Add mushrooms, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 189,
    name: 'Rice with mushrooms, tomatoes and broccoli',
    products: [
      'rice',
      'mushrooms',
      'tomatoes',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice and broccoli until soft. Add tomatoes, mushrooms, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 190,
    name: 'Rice with paprika, carrots, tomatoes and broccoli',
    products: [
      'rice',
      'carrots',
      'tomatoes',
      'paprika',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, carrots and broccoli until soft. Add tomatoes, paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 191,
    name: 'Rice with paprika, tomatoes and broccoli',
    products: [
      'rice',
      'tomatoes',
      'paprika',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice and broccoli until soft. Add tomatoes, paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 192,
    name: 'Rice with paprika, lentils, tomatoes and broccoli',
    products: [
      'rice',
      'tomatoes',
      'paprika',
      'lentils',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils and broccoli until soft. Add tomatoes, paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 193,
    name: 'Rice with paprika, lentils and broccoli',
    products: [
      'rice',
      'paprika',
      'lentils',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils and broccoli until soft. Add paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 194,
    name: 'Rice with carrots, lentils and broccoli',
    products: [
      'rice',
      'carrots',
      'lentils',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, carrots, lentils and broccoli until soft. Add coconutmilkand spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 195,
    name: 'Rice with paprika and broccoli',
    products: ['rice', 'paprika', 'broccoli', 'coconutmilk', 'spices'],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice and broccoli until soft. Add paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 196,
    name: 'Rice with paprika, zucchini and broccoli',
    products: [
      'rice',
      'paprika',
      'zucchini',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, zucchini and broccoli until soft. Add paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 197,
    name: 'Rice with paprika, lentils, zucchini and broccoli',
    products: [
      'rice',
      'paprika',
      'lentils',
      'zucchini',
      'broccoli',
      'coconutmilk',
      'spices',
    ],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils, zucchini and broccoli until soft. Add paprika, coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
  {
    id: 198,
    name: 'Rice with lentils and zucchini',
    products: ['rice', 'lentils', 'zucchini', 'coconutmilk', 'spices'],
    image: 'images/riceWithVegetables.jpeg',
    instruction:
      'Cook rice, lentils and zucchini until soft. Add coconutmilk and spices and cook it for around 10 minutes.',
    isBookmarked: false,
  },
]

export default recipesData
